version: "3.7"
services:

# redis 설정
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
    network_mode: "host"

# 서버 설정
  backend:
    image: gengminy/hifi-dev:dev
    container_name: backend
    network_mode: "host"
    env_file:
      - .env

# nginx 설정
  nginx:
    network_mode: "host"
    depends_on:
      - backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
