version: "3.7"
services:

# redis 설정
  redis:
    image: "redis:alpine"
    network_mode: "host"

# 서버 설정
  backend:
    image: gengminy/hifi-dev:dev
    container_name: backend
    network_mode: "host"
    env_file:
      - .env

# 리액트 설정
  frontend:
    image: gengminy/hififront:main
    container_name: frontend
    network_mode: "host"

# nginx 설정
  nginx:
    network_mode: "host"
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
