version: "3.7"
services:
  backend:
    image: gengminy/hifi-dev:dev
    container_name: backend
    hostname: backend
    env_file:
      - .env
    expose:
      - '8000'

# 내부 db 설정
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
    networks:
      - postgres           

  nginx:
    depends_on:
      - backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
 
