version: "3.7"
services:
  # redis 설정
  redis:
    image: "redis:alpine"
    # network_mode: "host"
    ports:
      - "6379:6379"

  # 서버 설정
  backend:
    image: squirmm/hongeat-dev:dev
    container_name: backend
    hostname: backend
    env_file:
      - .env
    expose:
      - "8080"

  # # 리액트 설정
  # frontend:
  #   image: gengminy/hififront:main
  #   container_name: client-prod
  #   hostname: client-prod
  #   network_mode: "host"

  # nginx 설정
  nginx:
    depends_on:
      - backend
      # - frontend
      - redis
    # network_mode: "host"
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
